apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers
  name: customers
  namespace: cnj

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: customers
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - image: ghcr.io/omar-p/cnj-basics:latest
        imagePullPolicy: IfNotPresent
        name: cnj-basics
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
