apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customers
  name: customers
  namespace: cnj
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customers
  type: LoadBalancer
status:
  loadBalancer: {}
